name: working_time_management
description: "A new Flutter project."

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
